import { ProjectSpecification } from './project-specification'
import { LanguageDefinition } from './project-types'
import { TemplateDefinition } from './template-registry'
import { PythonToolchain, JavaToolchain, TypeScriptJavaScriptToolchain } from './toolchain-abstraction'
import { FrameworkDefinitions, getFrameworkDefinition } from './framework-registry'

/** Repository Generator — Creates a project workspace with directory structure,
 * file generation, and baseline configuration.
 *
 * Responsibilities:
 * - create project workspace
 * - create directory structure
 * - create files from templates
 * - initialize Git metadata
 * - generate baseline configuration
 * - generate README
 * - generate dependency configuration
 * - generate test structure
 *
 * Security:
 * - Validates path traversal
 * - Prevents writing outside workspace
 * - Safe file creation only
 */
export class RepositoryGenerator {
  /** Base workspace root (configured per organization). */
  private workspaceRoot: string

  constructor(workspaceRoot: string) {
    this.workspaceRoot = workspaceRoot
  }

  /** Creates a new project workspace based on a specification. */
  async createProject(spec: ProjectSpecification): Promise<string> {
    // 1. Validate the specification
    if (!isValidProjectSpec(spec)) {
      throw new Error('Invalid project specification')
    }

    // 2. Create workspace directory
    const projectDir = `${this.workspaceRoot}/${spec.projectId}`
    await this.ensureDirectory(projectDir)

    // 3. Create directory structure based on language/framework
    await this.createDirectoryStructure(projectDir, spec)

    // 4. Generate files from templates
    await this.generateFiles(projectDir, spec)

    // 5. Initialize Git metadata
    await this.initializeGit(projectDir)

    // 6. Generate baseline configuration and README
    await this.generateBaseline(projectDir, spec)

    return projectDir
  }

  /** Ensures a directory exists. */
  private async ensureDirectory(path: string): Promise<void> {
    // In a real implementation, this would use fs.mkdirp or similar
    // Here we just validate the path is within workspace
    if (!path.startsWith(this.workspaceRoot)) {
      throw new Error('Path traversal detected: directory outside workspace')
    }
  }

  /** Creates the directory structure for the project. */
  private async createDirectoryStructure(projectDir: string, spec: ProjectSpecification): Promise<void> {
    const languageDef = LanguageDefinitions[spec.language]
    if (!languageDef) throw new Error(`Unsupported language: ${spec.language}`)

    // Create language-specific subdirectories
    const subdirs = ['src', 'tests', 'config']
    for (const subdir of subdirs) {
      await this.ensureDirectory(`${projectDir}/${subdir}`)
    }
  }

  /** Generates files from templates based on the project specification. */
  private async generateFiles(projectDir: string, spec: ProjectSpecification): Promise<void> {
    const templateId = this.getTemplateId(spec)
    const template = getTemplateDefinition(templateId)
    if (!template) throw new Error(`No template found for: ${templateId}`)

    // Create each file in the template's file structure
    for (const [path, contentLines] of Object.entries(template.fileStructure)) {
      const fullPath = `${projectDir}/${path}`
      await this.writeFile(fullPath, contentLines.join('\n'))
    }

    // Also generate dependency configuration if the template has dependencies
    if (template.dependencies && template.dependencies.length > 0) {
      await this.writeFile(
        `${projectDir}/requirements.txt`,
        template.dependencies.join('\n')
      )
    }
  }

  /** Gets the template ID based on the project specification. */
  private getTemplateId(spec: ProjectSpecification): string {
    // Simple mapping: language + framework + project type -> template ID
    const framework = spec.framework || 'none'
    return `${spec.language}_${framework}_${spec.projectType}_baseline`
  }

  /** Initializes Git metadata in the project directory. */
  private async initializeGit(projectDir: string): Promise<void> {
    // Placeholder - in a real implementation, this would run `git init`
    // and create a .gitignore file
    await this.writeFile(`${projectDir}/.gitignore`, '')
  }

  /** Generates baseline configuration and README. */
  private async generateBaseline(projectDir: string, spec: ProjectSpecification): Promise<void> {
    // Generate README.md
    const readmeContent = [
      `# ${spec.projectId}`,
      '',
      '## Project Specification',
      `- Type: ${spec.projectType}`,
      `- Language: ${spec.language}`,
      `- Framework: ${spec.framework || 'none'}`,
      `- Target Platform: ${spec.targetPlatform}`,
      '',
      '## Generation',
      `- Generated by Maurya AI Factory`,
      `- Date: ${new Date().toISOString()}`,
    ].join('\n')

    await this.writeFile(`${projectDir}/README.md`, readmeContent)

    // Generate configuration file based on language
    await this.generateConfigFile(projectDir, spec)
  }

  /** Generates language-specific configuration file. */
  private async generateConfigFile(projectDir: string, spec: ProjectSpecification): Promise<void> {
    const languageDef = LanguageDefinitions[spec.language]
    if (!languageDef) return

    if (spec.language === 'python') {
      const content = 'name = \"${projectId}\"\nversion = \"0.1.0\"\ndependencies = []\n'
      await this.writeFile(`${projectDir}/pyproject.toml`, content)
    } else if (spec.language === 'java') {
      const content = '<project><modelVersion>4.0.0</modelVersion><artifactId>${projectId}</artifactId><version>1.0.0</version></project>'
      await this.writeFile(`${projectDir}/pom.xml`, content)
    } else if (spec.language === 'typescript' || spec.language === 'javascript') {
      const content = '{\n  "name": "${projectId}",\n  "version": "0.1.0"\n}'
      await this.writeFile(`${projectDir}/package.json`, content)
    }
  }

  /** Writes a file to the workspace. */
  private async writeFile(path: string, content: string): Promise<void> {
    // Security: validate path is within workspace
    if (!path.startsWith(this.workspaceRoot)) {
      throw new Error('Path traversal detected: file outside workspace')
    }
    // Placeholder - in real implementation, use fs.writeFile
    // For now, just validate
  }
}

/** Factory utility functions. */
export function isValidProjectSpec(spec: ProjectSpecification): boolean {
  return (
    spec.projectId !== undefined &&
    spec.organizationId !== undefined &&
    spec.projectType !== undefined &&
    spec.language !== undefined
  )
}

/** Creates a RepositoryGenerator instance. */
export function createRepositoryGenerator(workspaceRoot: string): RepositoryGenerator {
  return new RepositoryGenerator(workspaceRoot)
}